### PR TITLE
Replace static image of the osm-liberty style with interactive map

### PR DESCRIPTION
**Pull request by spinF**
Is there a special reason, that the osm-liberty style uses a static image on the styles-page?
If not, here is a PR, that removes that static image and replaces it with an interactive map, like it's done for the other styles.

This change removes the static image `img/osm-liberty.jpg` from the styles page.
Instead it uses the style located at http://osm-liberty.lukasmartinelli.ch/style.json to render an interactive map like for the other styles on the page.

### CODE REVIEW

**Comment by lukasmartinelli** [comment]
Ah it is bit bad but the Natural Earth raster tiles I use in OSM Liberty are not HTTPS - and therefore I cannot include them.

**Comment by spinF** [comment]
OK, so what about this?
If the zoom level is limited to z6+, there'd be no need for loading Natural Earth tiles.
I adapted the patch to only show zoom levels starting with z6.

**Comment by lukasmartinelli** [comment]
> If the zoom level is limited to z6+, there'd be no need for loading Natural Earth tiles.

Wow clever idea!! :+1: Thanks.

**Comment by spinF** [comment]
An even better workaround would be to replace the URL in the style with https://klokantech.github.io/naturalearthtiles/tiles/natural_earth_2_shaded_relief.raster/{z}/{x}/{y}.png , or if you disabled automatic redirection from https://lukasmartinelli.github.io/naturalearthtiles to http://naturalearthtiles.org , you could serve them via https://lukasmartinelli.github.io/naturalearthtiles/ .

Github automatically provides you with a HTTPS certificate for the ‹username›.github.io subdomains, so that way the tiles could be served over HTTPS.

**Comment by klokan** [comment]
I have made the fork of @lukasmartinelli naturalearthtiles on our github - to make the github serve it on https. @spinF was faster on discovering this then me writing the note here.

Could you guys please display the styles uncrippled - with tiles from HTTPS?

(Lukas, feel free to load it from our fork of your gh-pages - or from another HTTPS location which you will be sure is going to be available in future).

**Comment by lukasmartinelli** [comment]
Thanks. Sorry for the commit storm..now works.

**Pull request merged**
